# Generated by Django 3.2.12 on 2022-10-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('customer_id', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('password', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customer',
            },
            bases=('AdminUser.mybasemodel',),
        ),
        migrations.AlterModelOptions(
            name='bookorder',
            options={'verbose_name': 'Book Orders', 'verbose_name_plural': 'Book Order'},
        ),
    ]
