# Generated by Django 3.2.12 on 2022-10-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('Order', '0003_rename_phone_no_customer_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('review_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=100)),
                ('review_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Book Reviews',
                'verbose_name_plural': 'Book Review',
            },
            bases=('AdminUser.mybasemodel',),
        ),
    ]
