# Generated by Django 3.2.12 on 2022-10-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('Order', '0004_bookreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('order_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('sub_total', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
