# Generated by Django 3.2.12 on 2022-10-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_onlinebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinebook',
            old_name='Author_write_year',
            new_name='author_write_year',
        ),
    ]
