# Generated by Django 3.2.12 on 2022-10-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminUser', '0002_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrearyCard',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('standard', models.IntegerField()),
                ('division', models.CharField(blank=True, max_length=100)),
                ('sr_no', models.IntegerField()),
                ('phone_no', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
