# Generated by Django 3.2.12 on 2022-10-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('BookStole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAvaliable',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('first_year', models.IntegerField()),
                ('second_year', models.IntegerField()),
                ('third_year', models.IntegerField()),
                ('MPSC', models.IntegerField()),
                ('UPS', models.IntegerField()),
                ('god', models.IntegerField()),
                ('good_thought', models.IntegerField()),
                ('spoken_english', models.IntegerField()),
                ('general_knowledge', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
