# Generated by Django 3.2.12 on 2022-10-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('BookStole', '0003_remove_bookavaliable_general_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
