# Generated by Django 3.2.12 on 2022-10-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStole', '0004_studentform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookavaliable',
            options={'verbose_name': 'Book avaliables', 'verbose_name_plural': 'Book Avaliable'},
        ),
        migrations.AlterModelOptions(
            name='librearycard',
            options={'verbose_name': 'Libreary cards', 'verbose_name_plural': 'Libreary Card'},
        ),
        migrations.AlterModelOptions(
            name='studentform',
            options={'verbose_name': 'Student Forms', 'verbose_name_plural': 'Student Form'},
        ),
    ]
