# Generated by Django 3.2.12 on 2022-10-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRegister',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('book_name', models.CharField(blank=True, max_length=100)),
                ('standard', models.IntegerField()),
                ('division', models.CharField(blank=True, max_length=100)),
                ('book_writer', models.CharField(blank=True, max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
