# Generated by Django 3.2.12 on 2022-10-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLogin',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
        migrations.AlterModelOptions(
            name='bookregister',
            options={'verbose_name': 'Book Registers', 'verbose_name_plural': 'Book Register'},
        ),
    ]
