# Generated by Django 3.2.12 on 2022-10-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('Account', '0002_auto_20221007_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSearch',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('book_title', models.CharField(max_length=100)),
                ('writer_name', models.CharField(blank=True, max_length=100)),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
