# Generated by Django 3.2.12 on 2022-10-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_booksearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklogin',
            options={'verbose_name': 'Book Logins', 'verbose_name_plural': 'Book Login'},
        ),
        migrations.AlterModelOptions(
            name='booksearch',
            options={'verbose_name': 'Book Searchs', 'verbose_name_plural': 'Book Search'},
        ),
    ]
