# Generated by Django 3.2.12 on 2022-10-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_auto_20221007_0807'),
        ('Account', '0004_auto_20221007_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoutBook',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
