# Generated by Django 3.2.12 on 2022-10-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminUser', '0002_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInform',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.IntegerField()),
                ('book_no', models.IntegerField()),
                ('book_publish', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
