# Generated by Django 3.2.12 on 2022-10-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0002_addstudent'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('chapter', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
        migrations.AlterField(
            model_name='authorinform',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='authorinform',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
