# Generated by Django 3.2.12 on 2022-10-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20221006_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorinform',
            options={'verbose_name': 'Author Informs', 'verbose_name_plural': 'Author Informations'},
        ),
        migrations.AlterModelOptions(
            name='issuebook',
            options={'verbose_name': 'Issue Books', 'verbose_name_plural': 'Issue'},
        ),
    ]
