# Generated by Django 3.2.12 on 2022-10-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20221007_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={'verbose_name': 'Issue Books', 'verbose_name_plural': 'Issue Book'},
        ),
    ]
