# Generated by Django 3.2.12 on 2022-10-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AdminUser.mybasemodel')),
                ('book_name', models.CharField(blank=True, max_length=100)),
                ('book_writer', models.CharField(blank=True, max_length=100)),
                ('no_book', models.IntegerField()),
                ('book_type', models.CharField(max_length=100)),
                ('book_publish_year', models.IntegerField()),
            ],
            bases=('AdminUser.mybasemodel',),
        ),
    ]
